import React, { useState } from 'react';
import { Box, Typography, Collapse, IconButton, Chip } from '@mui/material';
import { 
  InformationCircleIcon,
  ChevronDownIcon,
  ChevronUpIcon 
} from '@heroicons/react/24/outline';

const AnswerContext = ({ sources, confidence }) => {
  const [expanded, setExpanded] = useState(false);

  if (!sources || sources.length === 0) {
    return null;
  }

  // Extract topics from sources
  const topics = new Set();
  sources.forEach(source => {
    if (source.section) {
      topics.add(source.section);
    }
    // Extract from filename
    const filename = source.filename || '';
    if (filename.includes('Security')) topics.add('Security');
    if (filename.includes('AI')) topics.add('AI');
    if (filename.includes('Performance')) topics.add('Performance');
    if (filename.includes('Resilience')) topics.add('Resilience');
  });

  const topicsList = Array.from(topics).slice(0, 5);

  return (
    <Box
      sx={{
        mt: 3,
        p: 2.5,
        backgroundColor: '#F8F9FA',
        borderRadius: '12px',
        border: '1px solid',
        borderColor: 'divider',
      }}
    >
      <Box
        sx={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          cursor: 'pointer',
        }}
        onClick={() => setExpanded(!expanded)}
      >
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <InformationCircleIcon style={{ width: 18, height: 18, color: '#6B7280' }} />
          <Typography
            variant="body2"
            sx={{
              fontWeight: 600,
              color: 'text.secondary',
              fontSize: '0.875rem',
            }}
          >
            Why this answer?
          </Typography>
        </Box>
        <IconButton size="small" sx={{ color: 'text.secondary' }}>
          {expanded ? (
            <ChevronUpIcon style={{ width: 18, height: 18 }} />
          ) : (
            <ChevronDownIcon style={{ width: 18, height: 18 }} />
          )}
        </IconButton>
      </Box>

      <Collapse in={expanded}>
        <Box sx={{ mt: 2 }}>
          <Typography
            variant="body2"
            sx={{
              color: 'text.secondary',
              mb: 2,
              lineHeight: 1.6,
              fontSize: '0.8125rem',
            }}
          >
            This answer was generated by analyzing {sources.length} relevant{' '}
            {sources.length === 1 ? 'source' : 'sources'} from the LinuxONE documentation.
          </Typography>

          {topicsList.length > 0 && (
            <Box>
              <Typography
                variant="caption"
                sx={{
                  color: 'text.secondary',
                  fontWeight: 600,
                  display: 'block',
                  mb: 1,
                  fontSize: '0.75rem',
                }}
              >
                Topics covered:
              </Typography>
              <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
                {topicsList.map((topic, index) => (
                  <Chip
                    key={index}
                    label={topic}
                    size="small"
                    sx={{
                      backgroundColor: 'white',
                      border: '1px solid',
                      borderColor: 'divider',
                      color: 'text.secondary',
                      fontSize: '0.75rem',
                      height: '24px',
                      fontWeight: 500,
                    }}
                  />
                ))}
              </Box>
            </Box>
          )}

          {confidence && (
            <Box sx={{ mt: 2, pt: 2, borderTop: '1px solid', borderColor: 'divider' }}>
              <Typography
                variant="caption"
                sx={{
                  color: 'text.secondary',
                  fontSize: '0.75rem',
                  display: 'block',
                }}
              >
                <strong>Confidence level:</strong> The answer has{' '}
                {confidence === 'high' && 'high confidence based on strong source matches'}
                {confidence === 'medium' && 'medium confidence with good source relevance'}
                {confidence === 'low' && 'lower confidence - consider refining your query'}
              </Typography>
            </Box>
          )}
        </Box>
      </Collapse>
    </Box>
  );
};

export default AnswerContext;

// Made with Bob